version: "2.4"

services:

  validator:
    restart: unless-stopped
    container_name: prysm-validator-client
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    volumes:
      - ./prysmvalidator-data:/var/lib/prysm
      - ./wallet:/var/lib/prysm/wallet
    ports:
      - 8081:8081/tcp
    command:
      - --datadir=/var/lib/prysm
      - --wallet-dir=/var/lib/prysm/wallet
      - --beacon-rpc-provider=${CC_NODE}
      - --graffiti=${GRAFFITI}
      - --verbosity=${LOG_LEVEL}
      - --${NETWORK}
      - --enable-doppelganger
      - --accept-terms-of-use
      - --wallet-password-file=/var/lib/prysm/wallet/password.txt
      - --monitoring-host=0.0.0.0
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}