version: "2.4"

services:

  validator-import:
    image: ${PRYSM_IMAGE}
    command: |
      accounts import
      --accept-terms-of-use
      --keys-dir=/var/lib/prysm/keys/validator_keys
      --account-password-file=/var/lib/prysm/keys/keystore_password.txt
      --wallet-password-file=/var/lib/prysm/keys/wallet_password.txt
    volumes:
      - ./keystore:/var/lib/prysm/keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2
  validator-list:
    image: ${PRYSM_IMAGE}
    command: |
      accounts list
      --accept-terms-of-use
      --wallet-password-file=/var/lib/prysm/keys/wallet_password.txt
    volumes:
      - ./keystore:/var/lib/prysm/keys/validator_keys
      - ./wallet:/home/.eth2validators/prysm-wallet-v2

  validator:
    restart: unless-stopped
    container_name: prysm-validator-client
    image: ${PRYSM_IMAGE}
    volumes:
      - ./wallet:/var/lib/prysm/wallet
      - ./config:/var/lib/prysm/config
      - ./keystore:/var/lib/prysm/keys
    ports:
      - 8081:8081/tcp
    command:
      - --accept-terms-of-use
      - --datadir=/var/lib/prysm
      - --config-file=/var/lib/prysm/config/config.yml
      - --chain-config-file=/var/lib/prysm/config/config.yml
      - --wallet-dir=/var/lib/prysm/wallet
      - --beacon-rpc-provider=${CC_NODE}
      - --graffiti=${GRAFFITI}
      - --verbosity=${LOG_LEVEL}
      - --enable-doppelganger
      - --wallet-password-file=/var/lib/prysm/keys/wallet_password.txt
      - --monitoring-host=0.0.0.0
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090/tcp
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - validator
    logging: 
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}-prometheus