version: '3.9'

services:

  execution:
    stop_grace_period: 30s
    container_name: el-nethermind
    restart: unless-stopped
    image: ${EL_IMAGE_VERSION}
    networks:
      - merge
    volumes:
      - ./data/execution/:/data
      - ./jwtsecret:/tmp/jwt/jwtsecret:ro
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8008:8008/tcp
    expose:
      - 8545
      - 8551
    command: 
      - --config=ropsten
      - --datadir=/data
      - --Metrics.Enabled=${EL_METRICS_ENABLED}
      - --Metrics.ExposePort=8008
      - --Metrics.NodeName=${EL_METRICS_NODENAME}
      - --Sync.SnapSync=${EL_SNAP_SYNC_ENABLED}
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.JwtSecretFile=/tmp/jwt/jwtsecret
      - --JsonRpc.AdditionalRpcUrls=["http://0.0.0.0:8551|http;ws|net;eth;subscribe;engine;web3;client"]
      - --HealthChecks.Enabled=true
      - --EthStats.Enabled=${EL_ETHSTATS_ENABLED}
      - --EthStats.Server=${EL_ETHSTATS_SERVER}
      - --EthStats.Name=${EL_ETHSTATS_NAME}
      - --EthStats.Secret=${EL_ETHSTATS_SECRET}
      - --EthStats.Contact=${EL_ETHSTATS_CONTACT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  beacon:
    stop_grace_period: 30s
    container_name: cl-beacon-teku
    restart: unless-stopped
    image: ${CL_IMAGE_VERSION}
    networks:
      - merge
    volumes:
      - ./data/consensus:/data
      - ./jwtsecret:/tmp/jwt/jwtsecret:ro
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5054:5054/tcp
    expose:
      - 5051
    command:
      - --network=ropsten
      - --data-beacon-path=/data/teku/beacon
      - --data-path=/data/teku
      - --data-storage-archive-frequency=2048
      - --data-storage-mode=PRUNE
      - --data-storage-non-canonical-blocks-enabled=false
      - --ee-endpoint=http://execution:8551
      - --validators-proposer-default-fee-recipient=${CL_FEE_RECIPIENT}
      - --Xee-version=kilnv2
      - --ee-jwt-secret-file=/tmp/jwt/jwtsecret
      - --Xnetwork-total-terminal-difficulty-override=${CL_TTD}
      - --p2p-discovery-bootnodes=${CL_BOOTNODES}
      - --p2p-enabled=true
      - --p2p-port=9000
      - --p2p-peer-upper-bound=${CL_TARGET_PEERS}
      - --rest-api-enabled=true
      - --rest-api-host-allowlist=*
      - --rest-api-interface=0.0.0.0
      - --rest-api-port=5051
      - --rest-api-cors-origins=*
      - --rest-api-docs-enabled=false
      - --metrics-enabled=true
      - --metrics-host-allowlist=*
      - --metrics-interface=0.0.0.0
      - --metrics-port=5054
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  init-validator:
    container_name: init-validator
    build: ./init
    networks:
      - merge
    volumes:
      - ./data/consensus:/data
      - ./keystore:/keystore

  validator:
    container_name: cl-validator-teku
    image: ${VL_IMAGE_VERSION}
    depends_on:
      init-validator:
        condition: service_completed_successfully
    networks:
      - merge
    ports:
      - 5056:5056
    volumes:
      - ./data/consensus:/data
    command: 
      - validator-client
      - --validators-graffiti=${VL_GRAFFITI}
      - --validator-keys=/data/validator/keys:/data/validator/passwords
      - --validators-proposer-default-fee-recipient=${CL_FEE_RECIPIENT}
      - --beacon-node-api-endpoint=http://beacon:5051
      - --metrics-enabled=true
      - --metrics-host-allowlist=*
      - --metrics-interface=0.0.0.0
      - --metrics-port=5056
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  merge:
    name: ropsten_network

