version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: prysm-consesus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./prysmconsensus-data:/var/lib/prysm
      #- ./genesis.ssz:/genesis/genesis.ssz # Testnets only
    ports:
      - 13000:13000/tcp
      - 12000:12000/udp
      - 4000:4000/tcp
    command:
      - --datadir=/var/lib/prysm/
      - --verbosity=${LOG_LEVEL}
      - --${NETWORK}
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --p2p-max-peers=${PEER_COUNT}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --http-web3provider=${EC_NODE}
      - --fallback-web3provider=${EC_FALLBACK_NODE1}
      - --fallback-web3provider=${EC_FALLBACK_NODE2}
      - --eth1-header-req-limit=150
      #- --genesis-state=/genesis/genesis.ssz # Testnet only
      - --accept-terms-of-use
    logging:
      driver: gcplogs