version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: prysm-consesus-client
    restart: unless-stopped
    image: ${PRYSM_IMAGE}
    volumes:
      - ./prysmconsensus-data:/var/lib/prysm
      - ./config:/var/lib/prysm/config
    ports:
      - 13000:13000/tcp
      - 12000:12000/udp
      - 3500:3500/tcp
      - 4000:4000/tcp
      - 8080:8080/tcp
    command:
      - --datadir=/var/lib/prysm/
      - --contract-deployment-block=${CONTRACT_DEPLOYMENT_BLOCK}
      - --bootstrap-node=/var/lib/prysm/config/bootnodes.yaml
      - --config-file=/var/lib/prysm/config/config.yml
      - --chain-config-file=/var/lib/prysm/config/config.yml
      - --verbosity=${LOG_LEVEL}
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --p2p-max-peers=50
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --http-web3provider=${EC_NODE}
      - --fallback-web3provider=${EC_FALLBACK_NODE1}
      - --fallback-web3provider=${EC_FALLBACK_NODE2}
      - --eth1-header-req-limit=150
      - --monitoring-host=0.0.0.0
      - --accept-terms-of-use
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}