version: '3.9'

services:
  nethermind:
    stop_grace_period: 1m
    container_name: nethermind-execution-client
    restart: unless-stopped
    image: nethermind/nethermind
    volumes:
      - ./nethermindexecution-data/:/nethermind/data
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545/tcp
    command: 
      - --config=${NETWORK}
      - --datadir=/nethermind/data
      - --log=${LOG_LEVEL}
      - --Metrics.Enabled=true
      - --Metrics.PushgatewayUrl=${METRICS_URL}
      - --Metrics.NodeName=${NODENAME}
      - --Init.WebSocketsEnabled=true
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.EnabledModules="Web3,Eth,Subscribe,Net"
      - --HealthChecks.Enabled=true
      - --Pruning.CacheMb=${PRUNING_CACHEMB}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"