version: '2.4'

services:

  nethermind:
    stop_grace_period: 1m
    container_name: nethermind-execution-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./nethermindexecution-data/:/nethermind/data
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545/tcp
    mem_limit: 14.8G
    command: 
      - --config=${NETHERMIND_NETWORK}
      - --datadir=/nethermind/data
      - --log=${NETHERMIND_LOG_LEVEL}
      - --Metrics.Enabled=true
      - --Metrics.PushGatewayUrl=${NETHERMIND_METRICS_URL}
      - --Metrics.NodeName=${NETHERMIND_NODENAME}
      - --Init.WebSocketsEnabled=true
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net]
      - --HealthChecks.Enabled=true
      - --Pruning.CacheMb=${NETHERMIND_PRUNING_CACHEMB}
      - --EthStats.Enabled=${ETHSTATS_ENABLED}
      - --EthStats.Server=${ETHSTATS_SERVER}
      - --EthStats.Name=${INSTANCE_NAME}
      - --EthStats.Secret=${ETHSTATS_SECRET}
      - --EthStats.Contact=${ETHSTATS_CONTACT}
    logging:
      driver: gcplogs