version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: teku-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    user: root
    volumes:
      - ./teku-consensus-data:/var/lib/teku
    # ports:
    #   - 9000:9000/tcp
    #   - 9000:9000/udp
    #   - 5051:5051/tcp
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
    command:
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --logging=${LOG_LEVEL}
      - --network=${NETWORK}
      - --p2p-port=9000
      - --p2p-peer-upper-bound=${PEER_COUNT}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --eth1-endpoints=${EC_NODE}
      - --eth1-deposit-contract-max-request-size=150
      #- ${TEKU_RAPID_SYNC}
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  validator:
    restart: unless-stopped
    container_name: teku-validator-client
    image: ${IMAGE_VERSION}
    volumes:
      - ./teku-validator-data:/var/lib/teku
      - ./wallet:/var/lib/prysm/wallet
      - ./keys:/var/lib/prysm/keys
    depends_on:
      - consensus
    command:
      - validator-client
      - --beacon-node-api-endpoint=${EC_NODE}
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=${NETWORK}
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/validator-keys:/var/lib/teku/validator-passwords
      - --validators-graffiti=Nethermind
      - --validators-early-attestations-enabled=false
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"