version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: teku-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    user: root
    volumes:
      - ./tekuconsensus-data:/var/lib/teku
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5051:5051/tcp
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
    command:
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --logging=${LOG_LEVEL}
      - --network=${NETWORK}
      - --p2p-port=9000
      - --p2p-peer-upper-bound=${TEKU_PEER_COUNT}
      - --rest-api-host-allowlist=*
      - --rest-api-enabled=true
      - --eth1-endpoints=${EC_NODE}
      - --eth1-deposit-contract-max-request-size=150
      #- ${TEKU_RAPID_SYNC}
    logging:
      driver: gcplogs