version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lighthouse-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./lhconsensus-data:/var/lib/lighthouse
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5052:5052/tcp
    mem_limit: 28G
    command:
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir=/var/lib/lighthouse
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --network=${NETWORK}
      - --target-peers=${PEER_COUNT}
      - --eth1-endpoints=${EC_NODE}
      - --eth1-blocks-per-log-query=150
      - --debug-level=${LOG_LEVEL}
#      - --checkpoint-sync-url=${LH_RAPID_SYNC}
      - --validator-monitor-auto
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}