version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lighthouse-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./lhconsensus-data:/var/lib/lighthouse
    ports:
      - 13000:13000/tcp
      - 12000:12000/udp
      - 5052:5052/tcp
    command:
      - lighthouse
      - bn
      - --network=gnosis
      - --discovery-port=12000
      - --port=13000
      - --datadir=/var/lib/lighthouse
      - --http
      - --http-address=0.0.0.0
      - --enr-address=${PUBLIC_IP}
      - --enr-udp-port=12000
      - --eth1-endpoints=${EC_NODE}
      - --eth1-blocks-per-log-query=150
      - --debug-level=${LOG_LEVEL}
      - --target-peers=${PEER_COUNT}
    logging:
      driver: gcplogs
