version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lighthouse-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./lhconsensus-data:/var/lib/lighthouse
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5052:5052/tcp
    command:
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir=/var/lib/lighthouse
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --network=prater
      - --target-peers=${PEER_COUNT}
      - --eth1-endpoints=${EC_NODE}
      - --eth1-blocks-per-log-query=150
      - --debug-level=${LOG_LEVEL}
      - --validator-monitor-auto
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  validator-import:
      image: ${IMAGE_VERSION}
      command: |
        lighthouse account_manager validator import
        --password-file=/root/prater/keys/keystore_password.txt
        --reuse-password
        --directory=/root/prater/keys/validator_keys
        --datadir=/root/prater
      volumes:
        - ./keys:/root/prater/keys
        - ./validators:/root/prater/validators
  
  validator:
    image: ${IMAGE_VERSION}
    command: |
      lighthouse validator_client
      --validators-dir=/root/prater/validators
      --beacon-nodes=http://localhost:5052
      --graffiti=Nethermind
      --debug-level=${LOG_LEVEL}
      --network=prater
    network_mode: host
    volumes:
      - ./validators:/root/prater/validators
    depends_on:
      - consensus
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"