version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lighthouse-consensus-client
    restart: unless-stopped
    image: ${LIGHTHOUSE_IMAGE}
    volumes:
      - ./lhconsensus-data:/var/lib/lighthouse
      - ./gbc/config:/var/lib/lighthouse/config
    ports:
      - 13000:13000/tcp
      - 12000:12000/udp
      - 5052:5052/tcp
      - 5054:5054/tcp
    command:
      - lighthouse
      - bn
      - --discovery-port=12000
      - --testnet-dir=/var/lib/lighthouse/config
      - --datadir=/var/lib/lighthouse
      - --port=13000
      - --http
      - --http-address=0.0.0.0
      - --eth1-endpoints=${EC_NODE}
      - --eth1-blocks-per-log-query=150
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address=0.0.0.0
      - --validator-monitor-auto
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090/tcp
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - consensus
    logging: 
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}-prometheus