version: "2.4"

services:

  validator:
    restart: unless-stopped
    container_name: teku-validator-client
    image: consensys/teku:latest
    user: root
    volumes:
      - ./tekuvalidator-data:/var/lib/teku
      - ./keystore:/var/lib/teku/keystore
    ports:
      - 8008:8008/tcp
    environment:
      - JAVA_OPTS=-XX:SoftMaxHeapSize=2g -Xmx4g
    command:
      - validator-client
      - --beacon-node-api-endpoint=${CC_NODE}
      - --data-path=/var/lib/teku
      - --log-destination=CONSOLE
      - --network=auto
      - --validators-graffiti=${GRAFFITI}
      - --validators-keystore-locking-enabled=true
      - --validator-keys=/var/lib/teku/keystore:/var/lib/teku/keystore/secrets
      - --validators-early-attestations-enabled=false
      - --metrics-enabled=true
      - --metrics-port=8008
      - --metrics-interface=0.0.0.0
      - --metrics-host-allowlist=*
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090/tcp
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - validator
    logging: 
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}-prometheus