version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lodestar-consensus-client
    restart: unless-stopped
    image: ${IMAGE_VERSION}
    volumes:
      - ./lsconsensus-data:/var/lib/lodestar/consensus
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9596:9596/tcp
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
    command: 
      - beacon 
      - --rootDir=/var/lib/lodestar/consensus
      - --network=${NETWORK}
      - --logFile=/var/lib/lodestart/consensus/logs/beacon.log 
      - --logLevelFile=${LOG_LEVEL}
      - --api.rest.enabled 
      - --api.rest.host=0.0.0.0
      - --network.discv5.bindAddr="/ip4/0.0.0.0/udp/9000"
      - --network.localMultiaddrs="/ip4/0.0.0.0/tcp/9000"
      - --eth1.providerUrl=${EC_NODE}
      - --weakSubjectivitySyncLatest=${LS_RAPID_SYNC}
    logging:
      driver: gcplogs