version: "2.4"

services:

  consensus:
    stop_grace_period: 1m
    container_name: lodestar-consensus-client
    restart: unless-stopped
    image: chainsafe/lodestar:latest
    volumes:
      - ./lsconsensus-data:/var/lib/lodestar/consensus
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9596:9596/tcp
      - 8008:8008/tcp
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
    command: 
      - beacon 
      - --rootDir=/var/lib/lodestar/consensus
      - --network=${NETWORK}
      - --logFile=/var/lib/lodestart/consensus/logs/beacon.log 
      - --logLevelFile=${LOG_LEVEL}
      - --api.rest.enabled 
      - --api.rest.host=0.0.0.0
      - --network.discv5.bindAddr="/ip4/0.0.0.0/udp/9000"
      - --network.localMultiaddrs="/ip4/0.0.0.0/tcp/9000"
      - --eth1.providerUrl=${EC_NODE}
      - --metrics.enabled
      - --weakSubjectivitySyncLatest=${LS_RAPID_SYNC}
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090/tcp
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - consensus
    logging: 
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}-prometheus