version: "2.4"

services:

  validator:
    restart: unless-stopped
    container_name: lighthouse-validator-client
    image: ${LIGHTHOUSE_IMAGE}
    volumes:
      - ./keystore:/var/lib/lighthouse/keystore
      - ./gbc/config:/var/lib/lighthouse/config
    command:
      - lighthouse
      - vc
      - --testnet-dir=/var/lib/lighthouse/config
      - --beacon-nodes=${CC_NODE}
      - --graffiti=${GRAFFITI}
      - --debug-level=${LOG_LEVEL}
      - --validators-dir=/var/lib/lighthouse/keystore
      - --secrets-dir=/var/lib/lighthouse/keystore/secrets
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}