version: "2.4"

services:

  validator:
    restart: unless-stopped
    container_name: lighthouse-validator-client
    image: ${LIGHTHOUSE_IMAGE}
    volumes:
      - ./keystore:/var/lib/lighthouse/keystore
    ports:
      - 5064:5064/tcp
    command:
      - lighthouse
      - vc
      - --beacon-nodes=${CC_NODE}
      - --graffiti=${GRAFFITI}
      - --network=${NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address=0.0.0.0
      - --validators-dir=/var/lib/lighthouse/keystore
      - --secrets-dir=/var/lib/lighthouse/keystore/secrets
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}