version: "3.9"

services:

  validator:
    restart: unless-stopped
    container_name: lighthouse-validator-client
    image: sigp/lighthouse:latest
    volumes:
      - ./lhvalidator-data:/root/.lighthouse
      - ./scripts:/root/scripts:ro
      - ./keystore:/root/validator_keys:ro
    ports:
      - 5064:5064/tcp
    command: sh /root/scripts/start-validator-client.sh

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090/tcp
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - validator