version: "2.4"

services:

  validator:
    restart: unless-stopped
    container_name: lighthouse-validator-client
    image: sigp/lighthouse:latest
    volumes:
      - ./keystore:/var/lib/lighthouse/keystore
    command:
      - lighthouse
      - vc
      - --beacon-nodes=${CC_NODE}
      - --graffiti=${GRAFFITI}
      - --network=${NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --validators-dir=/var/lib/lighthouse/keystore
      - --secrets-dir=/var/lib/lighthouse/keystore/secrets
    logging:
      driver: awslogs
      options:
        awslogs-create-group: "true"
        awslogs-stream: ${INSTANCE_NAME}