global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prysm-consensus-client"
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ["consensus:8080"]

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: <USERNAME>
      password: <PASSWORD>
    remote_timeout: 600s